Nueva intro
javascript-beer/javascript-beer.github.io pull request #4
Opened 2021-03-16 19:04 UTC by alexfernandez

El formateo no queda muy bien, y el texto puede ser mejorable. A ver qué opina @Pand-o-Ra ...

2021-03-16 20:28 UTC, felixzapata requested changes
Debería ser 

```<main>
	  <p>Charlamos con gente durante las cervezas de un evento online javascripter… pero sin evento.</p>
	  {children}
	  </main>
```

Cuando @Pand-o-Ra decida el texto lo añado

2021-03-16 20:53 UTC, alexfernandez commented
@felixzapata Corregido en el commit 983d27d.

2021-03-16 20:55 UTC, alexfernandez commented
@Pand-o-Ra Pincha en "Files Changed":
![image](https://user-images.githubusercontent.com/876570/111378486-27790a80-86a2-11eb-9bdd-98d0a6306d54.png)
y mira el texto, ahora mismo es "Charlamos con gente durante las cervezas de un evento online javascripter… pero sin evento.". Es una cabecera que va en la página encima de las galletas.

@felixzapata El formateo queda raruno, creo que le vendría bien algo de espaciado al `<p>`.

2021-03-17 07:32 UTC, Pand-o-Ra commented
Esto es lo que veo,  ¿es así?
Texto, ok. Formato... no veo cómo queda :S

[image: imagen.png]


El mar, 16 mar 2021 a las 21:55, Alex Fernández ***@***.***>)
escribió:

> @Pand-o-Ra <https://github.com/Pand-o-Ra> Pincha en "Files Changed":
> [image: image]
> <https://user-images.githubusercontent.com/876570/111378486-27790a80-86a2-11eb-9bdd-98d0a6306d54.png>
> y mira el texto, ahora mismo es "Charlamos con gente durante las cervezas
> de un evento online javascripter… pero sin evento.". Es una cabecera que va
> en la página encima de las galletas.
>
> @felixzapata <https://github.com/felixzapata> El formateo queda raruno,
> creo que le vendría bien algo de espaciado al <p>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/javascript-beer/javascript-beer.github.io/pull/4#issuecomment-800598385>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ASXEZLEIDMLJWG57PJPQSCLTD7AUXANCNFSM4ZJEVOGQ>
> .
>

2021-03-17 08:16 UTC, alexfernandez commented
Si el texto es OK, el formato lo puede revisar Félix que sabe más de eso :wink: ¡Gracias!

2021-03-17 18:34 UTC, closed without merging

2021-03-17 18:34 UTC, felixzapata commented
I am going to make the changes directly into the branch.